name: transport_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>= 2.17.0 < 3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.2
  
  intl: ^0.18.1
  bluetooth_print: ^4.3.0
  easy_localization: ^3.0.3
  ionicons: ^0.2.2
  flutter_launcher_icons: ^0.13.1
  pinput: ^3.0.1
  pdf: ^3.10.7
  printing: ^5.11.1
  blue_thermal_printer: 
  path_provider: ^2.1.1
  image: ^4.1.3
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  skeletons: ^0.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # bluetooth_thermal_printer: ^0.0.6
  # esc_pos_utils: ^1.1.0
  # print_bluetooth_thermal: ^1.0.9
  # esc_pos_utils_plus: ^2.0.1+6
  
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/bus traveler.jpg"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/translations/

  fonts:
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Poppins-ExtraLight
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf

    - family: Poppins-Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf

    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: amharic
      fonts:
        - asset: assets/fonts/sabaean.ttf